### ISSUE TITLE
Housekeeping of the ITU OB editor

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-editor#125]
* [ ] #126
* [ ] https://github.com/ituob/itu-ob-editor/issues/122
* [ ] #127

@SmartWolf1220 will be handling this. Thanks!

@strogonoff will be guiding you if you have any questions.

**Comment by strogonoff** [comment]
@ronaldtse I’m going to say we don’t necessarily need the *latest* Electron version, but at least a fresher Electron version. I think some newer Electron versions introduce restrictions on Node integration, which may require a bigger refactor of how files are written (unless restriction is configurable).

**Comment by jeromebelleman** [comment]
Hi @ronaldtse, @strogonoff, thanks for following up on all this. Any idea of how soon you'll manage to address all this? It's just to know how to organise myself. If it's only a few days, I'll just wait. If it's a few weeks or more, I'll set up a VM running an old Debian to try running the editor as it is in the meantime.

**Comment by jeromebelleman** [comment]
Running the snap works beautifully, thanks @strogonoff!

**Comment by strogonoff** [comment]
@jeromebelleman That’s great to know, thanks for checking! If OB editing GUI is packaged as an extension for Paneron, the existing documentation on ituob.org will still apply, except that initial setup regarding specifying repository URL and Github username/token would be revised.

**Comment by strogonoff** [comment]
@jeromebelleman Major apologies for misestimation, it turned out to be a bit more complicated than I anticipated. We have the app working on Debian now, however. We may need to make sure sync & password storage works, however (I believe the issue you reported with Paneron may also apply here).

Here is a screenshot of the app working on Debian:
![b7fc199d-614b-4f08-8d37-0ab6ab76b0ff](https://github.com/user-attachments/assets/6070ec13-a590-4a2c-9d57-72ead392bb6d)

**Comment by strogonoff** [comment]
Hi @jeromebelleman,

If you have time, here is the upcoming release, which was so far confirmed to work on Ubuntu, Debian and Windows and to be published hopefully tomorrow (pending resolution of a few minor issues): [see .deb and .AppImage build artifacts here](https://github.com/ituob/itu-ob-editor/actions/runs/12390689624).

Note that in order for the app to work you might need to have `gnome-keyring` installed, or a KDE equivalent. If you experience an issue where the app is unable to sync and asks for Git password (which, in case of Github, would be your Classic developer token) at startup every time, then perhaps Electron could not find safe storage API to use. Unfortunately, I’m unable to find a complete list of supported packages, but I think `gnome-keyring` is one of them.

Some screenshots, one from Ubuntu and one from Debian:

![IMG_5418](https://github.com/user-attachments/assets/58f39bbe-f352-4643-b5e0-5cc09cc39bd8)
![IMG_5416 2](https://github.com/user-attachments/assets/1dac658c-7595-4b3b-b618-6f2ad09f1038)

**Comment by jeromebelleman** [comment]
Thanks @strogonoff,

I tried <https://github.com/ituob/itu-ob-editor/actions/runs/12462432548>. It runs, although complains it can't find the executable when I run `itu-ob-editor`, so I resort to directly running `/opt/ITU OB Editor/itu-ob-editor` instead:

```
debian@debian:~$ itu-ob-editor 
/usr/bin/itu-ob-editor: line 2: /usr/bin/itu-ob-editor.bin: No such file or directory
```

I enter an empty repository URL: <https://github.com/royarthurflynn/ob>

The *Offline – Please wait a moment" message appears. I hit the *Synchronize later* button.

Then when I select a cut-off date, set the edition number, I need to click the date in the calendar again, otherwise the *Commit* button remains greyed out.

When I hit the green *Synchronize* button, I keep getting the *Offline – Please wait a moment* message.

It's possible I'm doing something wrong, or that there's something wrong with my repository. Messages on the terminal, with the ones that printed when I hit the last *Offline* message:

```
15:50:13.565 › C/settings: Configuring w/path /home/debian/.config/ITU Operational Bulletin Editor/ituob-settings.yaml
15:50:13.586 › C/settings: Register API endpoints
15:50:13.592 › C/initMain: DB: Reading backend config
15:50:13.600 › C/initMain: DB: Reading backend config for default
15:50:13.604 › C/settings: Register setting
15:50:13.609 › C/settings: Register setting
15:50:13.612 › C/settings: Register setting
15:50:13.612 › C/settings: Register setting
[39808:0120/155013.611626:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
15:50:13.624 › C/initMain: Missing settings present, requesting from the user [ 'db_default_gitRepoUrl' ]
15:50:13.627 › C/main: Opening window settings
Error occurred in handler for 'db-default-describe': No handler registered for 'db-default-describe'
15:50:28.794 › C/settings: Set value for setting db_default_gitRepoUrl
15:50:28.796 › C/settings: Commit new settings
15:50:28.797 › C/settings: Commit: Remove file
15:50:28.800 › C/settings: Commit: Write new file
15:50:33.718 › C/main: User provider all missing settings
15:50:33.719 › C/initMain: DB: Completing backend options for default
15:50:33.720 › C/initMain: DB: Initializing backend default
15:50:33.721 › C/db/isogit-yaml: Setting up IPC
15:50:33.722 › C/initMain: Initializing data model managers
15:50:33.723 › C/initMain: Initializing model manager for DB default
15:50:33.724 › C/initMain: Initializing model manager for DB default
15:50:33.725 › C/initMain: Initializing model manager for DB default
15:50:33.727 › C/main: Opening window default
15:50:34.320 › C/initMain: Initializing DB backend default
15:50:34.333 › C/db/isogit-yaml: Git has mismatching remote URL, reinitializing with: https://github.com/royarthurflynn/ob
15:50:34.334 › C/db/isogit: Initialize: Removing data directory
15:50:34.386 › C/db/isogit: Checking if clone exists
15:50:34.388 › C/db/isogit: Initializing
15:50:34.388 › C/db/isogit: Initialize: Ensuring data directory exists
15:50:34.389 › C/db/isogit: Initialize: Cloning https://github.com/royarthurflynn/ob
15:50:34.569 › C/db/isogit: Worker event: {
  type: 'message',
  data: { type: 'running', uid: 1, resultType: 'promise' }
}
15:50:34.983 › C/db/isogit: Worker event: {
  type: 'message',
  data: {
    type: 'result',
    uid: 1,
    complete: true,
    payload: { success: true }
  }
}
15:50:34.988 › C/db/isogit: Queueing sync now, lock is not busy
15:50:34.989 › C/db/isogit: Starting sync
15:50:34.995 › C/db/isogit: Pulling master with fast-forward merge
15:50:35.002 › C/db/isogit: Worker event: {
  type: 'message',
  data: { type: 'running', uid: 2, resultType: 'promise' }
}
15:50:35.568 › C/db/isogit: Worker event: {
  type: 'message',
  data: {
    type: 'error',
    uid: 2,
    error: {
      __error_marker: '$$error',
      message: 'Could not find master.',
      name: 'NotFoundError',
      stack: 'NotFoundError: Could not find master.\n' +
        '    at Function.ours [as expand] (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2030:11)\n' +
        '    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9535:3)\n' +
        '    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)\n' +
        '    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)\n' +
        '    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13'
    }
  }
}
15:50:35.570 › C/db/isogit: Failed to pull NotFoundError: Could not find master.
    at Function.ours [as expand] (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2030:11)
    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9535:3)
    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)
    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)
    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13
15:50:35.571 › NotFoundError: Could not find master.
    at Function.ours [as expand] (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2030:11)
    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9535:3)
    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)
    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)
    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13
15:50:35.575 › Handling Git error NotFoundError: Could not find master.
    at Function.ours [as expand] (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2030:11)
    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9535:3)
    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)
    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)
    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13
15:51:59.408 › C/ipc: Error handling request to model-issues-list-ids! Error: ENOENT: no such file or directory, scandir '/home/debian/.config/ITU Operational Bulletin Editor/ituob-data/issues': Error: ENOENT: no such file or directory, scandir '/home/debian/.config/ITU Operational Bulletin Editor/ituob-data/issues'}
15:52:14.237 › ITU OB: Failed to read publication meta, using defaults
15:52:14.322 › C/db: Committing objects [ 'issues/1' ] [
  { path: 'issues/1/amendments.yaml' },
  { path: 'issues/1/annexes.yaml' },
  { path: 'issues/1/general.yaml' },
  { path: 'issues/1/meta.yaml' }
] [
  'issues/1/amendments.yaml',
  'issues/1/annexes.yaml',
  'issues/1/general.yaml',
  'issues/1/meta.yaml'
] scheduled OB 1
15:52:14.323 › C/db/isogit: Staging and committing: issues/1/amendments.yaml, issues/1/annexes.yaml, issues/1/general.yaml, issues/1/meta.yaml
15:52:14.334 › C/db/isogit: Unstaging all changes
15:52:14.337 › C/db/isogit: Staging changes: issues/1/amendments.yaml, issues/1/annexes.yaml, issues/1/general.yaml, issues/1/meta.yaml using add()
15:52:14.386 › C/db/isogit: Committing with message scheduled OB 1
15:52:36.013 › C/db/isogit: Checking if clone exists
15:52:36.014 › C/db/isogit: Checking for uncommitted changes
15:52:36.015 › C/db/isogit: Checking for uncommitted changes
15:52:36.046 › C/db/isogit: Changed files: []
15:52:36.049 › C/db/isogit: Force resetting files
15:52:36.068 › C/db/isogit: Queueing sync now, lock is not busy
15:52:36.069 › C/db/isogit: Starting sync
15:52:36.071 › C/db/isogit: Pulling master with fast-forward merge
15:52:36.076 › C/db/isogit: Worker event: {
  type: 'message',
  data: { type: 'running', uid: 3, resultType: 'promise' }
}
15:52:36.521 › C/db/isogit: Worker event: {
  type: 'message',
  data: {
    type: 'error',
    uid: 3,
    error: {
      __error_marker: '$$error',
      message: "Cannot read properties of null (reading 'length')",
      name: 'TypeError',
      stack: "TypeError: Cannot read properties of null (reading 'length')\n" +
        '    at Function.expand (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2015:13)\n' +
        '    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9540:32)\n' +
        '    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)\n' +
        '    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)\n' +
        '    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13'
    }
  }
}
15:52:36.522 › C/db/isogit: Failed to pull TypeError: Cannot read properties of null (reading 'length')
    at Function.expand (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2015:13)
    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9540:32)
    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)
    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)
    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13
15:52:36.523 › TypeError: Cannot read properties of null (reading 'length')
    at Function.expand (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2015:13)
    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9540:32)
    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)
    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)
    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13
15:52:36.528 › Handling Git error TypeError: Cannot read properties of null (reading 'length')
    at Function.expand (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:2015:13)
    at pruneTags (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9540:32)
    at _pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:9737:7)
    at Object.pull (/opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/isomorphic-git/index.js:12096:5)
    at /opt/ITU OB Editor/resources/app.asar.unpacked/webpack:/node_modules/@riboseinc/coulomb/db/isogit-yaml/main/isogit/worker.js:43:13
```

Thanks,
-- Jérôme
