### ISSUE TITLE
Pushing Data to an Azure DevOps Repository

### ISSUE THREAD

**Issue by jeromebelleman** [ituob/itu-ob-editor#129]
- [x] I have looked at [the documentation for the app](https://www.ituob.org/docs/), and I still believe there is an issue.

**Describe the issue**

Not a problem with the app per se, more of a request to help us have Paneron push data to a git repository on the Azure DevOps we use at ITU.

**When does it happen?**

1. Start Paneron.
1. Hit *Add shared repository*.
1. Set the *Remote URL* to something like <https://dev.azure.com/ITUINT/tsbops/_git/foo>. This error message appears in red:

   > **There may have been an issue**
   > 
   > - There was a problem connecting. (Error: Unable to load state: safe storage API is not available)
   > - Please check repository URL and, if applicable, access credentials.
   > - Please check your connection.
   > - Wait in case repository hosting is experiencing downtime.
   > - Otherwise, please contact us and let us know the error message.

   Paneron prints to the terminal:

   ```
   Error occurred in handler for 'queryRemote': Error: Unable to load state: safe storage API is not available
       at loadState (/snap/paneron/x1/resources/app.asar/webpack:/src/state/manage.ts:44:11)
       at getAuth (/snap/paneron/x1/resources/app.asar/webpack:/src/repositories/main/remoteAuth.ts:27:19)
       at module.exports.queryGitRemote.main.handle.repoOpQueue.oneAtATime.url.url (/snap/paneron/x1/resources/app.asar/webpack:/src/repositories/main/index.ts:489:22)
       at performTask (/snap/paneron/x1/resources/app.asar/webpack:/src/utils.ts:55:26)
   ```

Opening <https://dev.azure.com/ITUINT/tsbops/_git/foo> in a browser leads to a Microsoft login page.

![image](https://github.com/user-attachments/assets/542c7fc2-99dd-4431-a5d7-70b90fabd9c9)

Maybe Paneron doesn't like this. Then again, `git clone https://dev.azure.com/ITUINT/tsbops/_git/foo` will work and I would have hoped Paneron did just that.

**Expected behavior**

The error not to show up as soon as I enter the URL. I tried to go further by typing my username and password, but the same error message kept appearing.

**Environment**

- OS: Debian 12.8
- Paneron v2.2.14

**Comment by jeromebelleman** [comment]
Cc'ing @Ulrica-shen

**Comment by strogonoff** [comment]
Thank you for filling @jeromebelleman.

This part:

> Error: Unable to load state: safe storage API is not available

Indicates that integration with Debian’s safe storage is not working properly. The app uses [Electron’s safeStorage API](https://electronjs.org/docs/latest/api/safe-storage), which I believe under the hood relies on Keychain on macOS and I believe whatever Microsoft’s equivalent is on Windows, but I will need to see how it is handled on Debian. [This is where the API is used](https://github.com/paneron/paneron/blob/b46a8ceb3ae900e361826c186276fc4982f26497/src/repositories/main/remoteAuth.ts#L24).

The way Paneron works is it would 1) save the secret using this API, and then 2) retrieve it during sync. So, if it’s not available, then it can’t work with remote Git repos.

**Comment by strogonoff** [comment]
> Opening https://dev.azure.com/ITUINT/tsbops/_git/foo in a browser leads to a Microsoft login page.

We don’t support OAuth currently, and rely on regular password authentication. In Github, one can be achieved with the help of PATs provisioned via Developer settings. I’m not sure about Azure.
